# -*- coding: utf-8 -*-
"""Geographic data visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qM8X5zhgz4qZ9T-0arYz57Irvk6iEOOk
"""

import plotly.express as px
import pandas as pd

# Built-in dataset for world countries
df = px.data.gapminder().query("year == 2007")

# 4 maps
fig1 = px.choropleth(df, locations="iso_alpha", color="lifeExp", title="Life Expectancy")
fig2 = px.choropleth(df, locations="iso_alpha", color="gdpPercap", title="GDP Per Capita")
fig3 = px.choropleth(df, locations="iso_alpha", color="pop", title="Population")
fig4 = px.choropleth(df, locations="iso_alpha", color="continent", title="Continent")

fig1.show()
fig2.show()
fig3.show()
fig4.show()

import pandas as pd
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

# Sample earthquake data (California region)
data = {
    'Latitude': [34.05, 36.77, 37.77, 32.72, 38.58],
    'Longitude': [-118.25, -119.42, -122.42, -117.16, -121.49],
    'Magnitude': [4.2, 3.5, 4.8, 3.9, 4.1]
}

df = pd.DataFrame(data)

# Plot
fig = plt.figure(figsize=(8, 10))
ax = plt.axes(projection=ccrs.PlateCarree())
ax.set_extent([-125, -114, 32, 42])
ax.coastlines()
ax.gridlines(draw_labels=True)

# Earthquake scatter plot
scatter = ax.scatter(
    df['Longitude'], df['Latitude'],
    s=df['Magnitude']**3,
    c=df['Magnitude'], cmap='YlOrBr',
    alpha=0.7, edgecolor='k', linewidth=0.5,
    transform=ccrs.PlateCarree()
)

# Colorbar
cbar = plt.colorbar(scatter, orientation='vertical', shrink=0.5, pad=0.05)
cbar.set_label('Magnitude')

plt.title("California Earthquakes", fontsize=14)
plt.show()

import folium

# Create a simple map centered over India
india_map = folium.Map(location=[21, 78], zoom_start=5)

folium.Marker([13,80],popup='Chennai',tooltip='click').add_to(india_map)
folium.Marker([19,72],popup='Mumbai',tooltip='click').add_to(india_map)
folium.Marker([22,88],popup='Kolkata',tooltip='click').add_to(india_map)
folium.Marker([28,77], popup="Delhi", tooltip='pinch to zoom').add_to(india_map)

india_map